title: Well Conditioned
description: Solving problems in the intersection of computational theory, data science, and software craft.

ga: UA-120212012-1

themeConfig:
  search: false
  nav:
    - text: Home
      link: /
    - text: Talks
      link: /talks/
    - text: Contact
      link: /contact/

markdown:
  lineNumbers: false
  anchor:
    permalink: true
    permalinkSymbol: 'ยง'
    permalinkBefore: false
  toc: 
    includeLevel: [2, 3]
